logging-level:
  dao: debug
  common: info
  domain: info
  service: info
  web: info

wechat:
  grant-type: client_credential
  appid: wxd19a1a5f30dea77c
  secret: 2fa7d4e5417f9404432c76793e99e91d
  originalid: gh_7e8ebd642fae
  token: Eason