spring:
  application:
    name: common
  profiles:
    active: dev

logging:
  level:
    xin:
      eason:
        dao: ${logging-level.dao}
        common: ${logging-level.common}
        domain: ${logging-level.domain}
        service: ${logging-level.service}
        web: ${logging-level.web}

wechat:
  grant-type: ${wechat.grant-type}
  appid: ${wechat.appid}
  secret: ${wechat.secret}
  originalid: ${wechat.originalid}
  token: ${wechat.token}
